# Generated by Django 2.0.4 on 2018-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180420_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='DEFAULT VALUE', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@123.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
