# Generated by Django 2.0.4 on 2018-04-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180420_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
