# Generated by Django 2.0.4 on 2018-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180527_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='college',
            new_name='collegename',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
