# Generated by Django 2.0.4 on 2018-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180528_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retypepassword',
            field=models.CharField(default='DEFAULT VALUE', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='user',
            name='collegename',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
