# Generated by Django 2.0.4 on 2018-05-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='loginemail',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='loginpassword',
        ),
    ]
