# Generated by Django 2.0.4 on 2018-05-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180529_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='loginemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='loginpassword',
            new_name='password',
        ),
    ]
